name: update-task-progress after pull request merged

on:
  pull_request_target:
    types: [closed]
    branches:
      - main  # 或者你希望触发CI的分支名称

      # 使用pull_request_target 而不是pull_request   因为pull_request不send fork分支触发的pr write right

jobs:
  build:
    if: github.event.pull_request.merged == true  # 只有当pull request被合并时才执行CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 替换为你需要的Python版本

    - name: Install dependencies
      run: |
        sudo apt install fonts-noto-cjk  
        python -m pip install --upgrade pip
        pip install -r assets/requirements.txt  # 如果你的项目有requirements.txt文件

    - name: Run Python script
      run: |
        python assets/update-task-progress.py  # 替换为你需要运行的Python脚本

    # Push the changes
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: updae task progress

